In [1]:
'''Analisis:
- All the data (list = patient with all values)
- BandPower = patient = 12 brain reagions = 5 bands = 1 value


- Lavels structure all patiens with one value = list (no shape)'''

'Analisis:\n- All the data (list = patient with all values)\n- BandPower = patient = 12 brain reagions = 5 bands = 1 value\n\n\n- Lavels structure all patiens with one value = list (no shape)'

In [24]:
#Multiple regression is like linear regression, but with more than one independent value, meaning that we try to predict a value based on two or more variables.
import numpy as np
import matplotlib.pyplot as plt
from numpy import savetxt
import pickle
import csv
from sklearn import linear_model
from sklearn.svm import SVC
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import pandas as pd
import seaborn as sns
import statsmodels.formula.api as smf
from sklearn.linear_model import LinearRegression
from sklearn import metrics

In [56]:
print(len(withEpoch))
print(len(withEpoch[0]))
print(len(withEpoch[0][0]))
print((withEpoch[0][0]))

12
5
187
[0.13687358079089113, 0.2608587434146743, 0.2634709782481588, 0.23186056614364345, 0.1746941654630223, 0.22303454863239516, 0.22338387489374834, 0.165122742061091, 0.28149714240020063, 0.21311961944059085, 0.27274317822200006, 0.26209577300936937, 0.18095155728812443, 0.26721362832545226, 0.25535714683676114, 0.2816374779758885, 0.2313726514074267, 0.34411657568466836, 0.2764397570721108, 0.20344666402225148, 0.13283199193915235, 0.09827671168129254, 0.2359445209752834, 0.1319458797798827, 0.11669918456687299, 0.12602264877987535, 0.1790845227147819, 0.31475497543366726, 0.26730307571284506, 0.21694616225060714, 0.09919560126907005, 0.25872068149191885, 0.18069227335237478, 0.305106691132682, 0.22475856251224757, 0.205901252760525, 0.274253289528396, 0.20762104838441048, 0.23458157887365075, 0.3218976285875164, 0.41045627432333043, 0.2876729373733401, 0.25770853643017855, 0.28553388461594126, 0.2525619445686872, 0.235086346985915, 0.23268168886201057, 0.2933904696762321, 0.179

In [3]:
with open("/Users/laianavarroolivella/Proyectos/EEG/2.BanPOwerEpoch12Chanels/list_final_EO.txt", "rb") as fp:   # Unpickling
    withEpoch = pickle.load(fp)

with open("/Users/laianavarroolivella/Proyectos/EEG/1.create12ChanelsXPatient/sorted_list_ECsave.txt", "rb") as fp:   # Unpickling
    sorted_list_EC_up = pickle.load(fp)

with open("/Users/laianavarroolivella/Proyectos/EEG/1.create12ChanelsXPatient/sorted_list_EO_save.txt", "rb") as fp:   # Unpickling
    sorted_list_EO_up = pickle.load(fp)

In [4]:
#Import the data to analise
#Open the file in universal line ending mode 
with open('/Users/laianavarroolivella/Proyectos/EEG/Files_EEG/TEIQue-SF.csv', 'rU') as infile:
  # read the file as a dictionary for each row ({header : value})
  data = {}
  reader = csv.DictReader(infile)
  for row in reader:
    for header, value in row.items():
      try:
        data[header].append(value)
      except KeyError:
        data[header] = [value]

# extract the variables you want
names = data['ID']
TeiQueSF_emotionality = data['TeiQueSF_emotionality']
TeiQueSF_wellBeing = data['TeiQueSF_well_being']

In [5]:
xCorr = []
for e in range(0,len(sorted_list_EO_up)):       #For each frequency band:
    hename = sorted_list_EO_up[e]   #Select the name of the patient
    hename = str(hename[:-7])  #Select only the number witout the extension 
    if hename in names:    #If this is in the testNames:
        indices = [i for i, s in enumerate(names) if hename in s] #Get the position of the testNames
        x = (float(TeiQueSF_wellBeing[int(indices[0])])) #Get the value of the patient in the test selected
        xCorr.append(x) #Add it in to the xCorr
    else:
        print("No esta"+hename)

In [13]:
#Epoch (samples data point) all incluede for each subject <- + band + brain region (concatenated)

#All Epochs ! Majoriti points <- find a ave
a = np.array(withEpoch)
print(a.shape)
b = a.T
print(b.shape)
c = b.reshape(187,60)
print(c.shape)

(12, 5, 187)
(187, 5, 12)
(187, 60)


In [9]:
#Lavels
Y = np.array(xCorr)
print(type(Y))
print(type(Y[0]))

<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [38]:
X_train, X_test, y_train, y_test = train_test_split(c, Y, test_size=0.2, random_state=None)

In [ ]:
# Training = normalise! - mean and standar desv.
# Test should be the same


In [27]:
print(X_train.shape)
print(X_test.shape)
print('\n')
print(y_train.shape)
print(y_test.shape)

(149, 5, 12)
(38, 5, 12)


(149,)
(38,)




In [40]:
regr = linear_model.LinearRegression().fit(X_train, y_train)

In [41]:
regr.score(X_train, y_train)

0.3127504605171769

In [42]:
regr.coef_

array([-1.08027846e+00,  1.08496097e+01, -9.02668152e+00,  1.64281838e+00,
        2.80228414e-01, -1.22665430e+01,  1.64273904e+01, -1.42900240e+00,
        2.07571409e+01, -2.27608770e+00, -1.57465432e+01, -6.93343454e+00,
        2.79467625e+00, -1.00744839e+00,  1.01104620e+00,  4.51907384e+00,
       -7.55761592e-02, -5.55501400e+00,  1.67277785e-01,  2.95795698e+00,
        4.45028130e+00,  6.98873747e-01, -9.45033703e-01, -6.25981344e+00,
        1.36530192e+00,  5.86478370e+00, -2.33863922e+00, -9.95258615e+00,
       -5.41398110e+00,  4.06465111e+00, -1.01737860e+00,  9.74207381e+00,
        4.39093632e+00,  8.29430732e+00, -1.30485333e+01, -3.35019030e+00,
       -1.11133018e+00, -2.18083328e+00,  1.96977214e+00,  2.08743512e+01,
        1.65190479e+01,  4.43653532e+01,  3.82185286e+01, -6.34156600e+01,
        1.42405736e+02, -2.79848331e+00, -1.65053534e+02, -2.08241317e+01,
       -1.47102736e+01,  8.44823234e+00, -2.11504018e+01,  3.89103777e+00,
       -1.24289503e+00, -

In [43]:
regr.intercept_

5.377772671619355

In [44]:
y_pred = regr.predict(X_test)

In [45]:
# MAE output is non-negative floating point. The best value is 0.0.
print(metrics.mean_absolute_error(y_test, y_pred))
# A non-negative floating point value (the best value is 0.0), or an array of floating point values, one for each individual target.
print(metrics.mean_squared_error(y_test, y_pred))
print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

1.550674114344988
12.494175008863406
3.5347100317937548


In [47]:
y_pred

array([  5.10908076,   5.18832987,   5.94051614,   5.97274679,
         5.66529845,   5.45863101,   5.12895805,   6.07526274,
         6.03976559,   5.50735286,   5.87573254,   5.65128134,
       -16.76765533,   5.91555935,   5.89089311,   4.99320052,
         5.1644762 ,   6.73041354,   5.77927634,   5.57614557,
         5.26582294,   6.35606118,   5.69230901,   3.54328787,
         7.26188704,   5.52159783,   5.08854701,   5.04187601,
         4.66894025,   5.99892787,   4.58568301,   5.56312186,
         5.24754648,   5.16580446,   3.79739861,   5.26842165,
         5.88479009,   4.57519832])

In [49]:
y_test

array([6.5       , 5.66666667, 6.33333333, 6.66666667, 5.83333333,
       5.83333333, 5.83333333, 4.        , 4.33333333, 6.83333333,
       4.66666667, 4.5       , 3.83333333, 4.33333333, 6.83333333,
       4.66666667, 5.83333333, 6.5       , 5.33333333, 6.83333333,
       3.        , 5.33333333, 6.5       , 5.        , 6.66666667,
       6.16666667, 6.33333333, 6.16666667, 6.16666667, 6.5       ,
       6.66666667, 4.5       , 6.33333333, 6.5       , 4.5       ,
       6.66666667, 6.5       , 6.33333333])

In [46]:
#The best possible score is 1.0 and it can be negative (because the model can be arbitrarily worse). 
print(regr.score(X_test, y_pred))

-11.373260566531844
